version: "3.7"

services:
  db:
    image: mysql:8.0
    environment:
      - 'MYSQL_USER=root'
      - 'MYSQL_ROOT_PASSWORD=my-secret-pw'
      - 'MYSQL_DATABASE=uhk'
    ports:
      - "3306:3306"
    restart: on-failure

  app:
    image: garbage-collectors
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/uhk
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=my-secret-pw
    restart: on-failure